
services:
  web:
    build: 
      dockerfile: web.Dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/app
  
  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    environment:
      - USER=ELIZABETH LIM MING HUI # Needs to run git config user.name "name" command first
      - EMAIL=2901233@sit.singaporetech.edu.sg # Follow by this git config user.email "email" command
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"   # Web UI
      - "9092:9092"   # Internal communication
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  db:
    image: postgres:latest
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql:/var/lib/postgresql

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:

